### ISSUE TITLE
Running this play project from intellij fails in compile error

### ISSUE THREAD

**Issue by aruld** [typesafehub/reactive-stocks-java8#7]
```
[info] Compiling 3 Scala sources and 10 Java sources to /Users/arul/github/reactive-stocks-java8/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.2. Compiling...
[info] LESS compiling on 1 source(s)
[info] CoffeeScript compiling on 1 source(s)
[info]   Compilation completed in 10.158 s
[error] javac: invalid source release: 1.8
[error] Usage: javac <options> <source files>
[error] use -help for a list of possible options
[error] (compile:compile) javac returned nonzero exit code
[error] application - 

! @6jliijm36 - Internal server error, for (GET) [/] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[The compilation failed without reporting any problem!]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1$$anonfun$apply$20.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1$$anonfun$apply$20.apply(PlayReloader.scala:235) ~[na:na]
	at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.11.2.jar:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:235) ~[na:na]
	at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:229) ~[na:na]
Caused by: sbt.compiler.CompileFailed: null
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77) ~[na:na]
	at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63) ~[na:na]
	at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21) ~[na:na]
	at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63) ~[na:na]
[warn] play - No application found at invoker init
```

I just could not run any of the sample java 8 project from intellij. any idea?

**Comment by narkesn** [comment]
I am also facing the same issue. Any solution for this?

Thanks

**Comment by gmethvin** [comment]
Based on the error message (`[error] javac: invalid source release: 1.8`), it seems like you may be using the wrong JDK version in IntelliJ.

**Comment by gmethvin** [comment]
But if you're trying to get help, I'd suggest doing so on the Play mailing list instead, and post the full error message.

**Comment by narkesn** [comment]
fixed this issue. problem was with java was referring to 1.8 and javac to 1.7.

Thanks,
